const foodLists = [
  {
    id: 1,
    name: "Nasi goreng juara",
    imageSrc: "./src/assets/nasigoreng.jpg",
    imageAlt: "Food List",
    price: "25.000",
    location: "Bandung",
  },
  {
    id: 2,
    name: "Kwetiaw 79",
    imageSrc: "./src/assets/kwetiaw.jpeg",
    imageAlt: "Food List",
    price: "35.000",
    location: "Bandung",
  },
  {
    id: 3,
    name: "Bubur ABC",
    imageSrc: "./src/assets/bubur.jpg",
    imageAlt: "Food List",
    price: "15.000",
    location: "Bandung",
  },
  {
    id: 4,
    name: "Nasi Kuning Bangka",
    imageSrc: "./src/assets/naskun.jpg",
    imageAlt: "Food List",
    price: "55.000",
    location: "Bandung",
  },
  {
    id: 5,
    name: "Mie Ramen Paster",
    imageSrc: "./src/assets/ramen.jpg",
    imageAlt: "Food List",
    price: "25.000",
    location: "Bandung",
  },
  {
    id: 6,
    name: "Martabak Mang adek",
    imageSrc: "./src/assets/martabak.jpg",
    imageAlt: "Food List",
    price: "45.000",
    location: "Bandung",
  },
  {
    id: 7,
    name: "Steak BDG",
    imageSrc: "./src/assets/steak.jpg",
    imageAlt: "Food List",
    price: "225.000",
    location: "Bandung",
  },
  {
    id: 8,
    name: "Nasi goreng ABU",
    imageSrc: "./src/assets/nasigoreng.jpg",
    imageAlt: "Food List",
    price: "35.000",
    location: "Bandung",
  },
  {
    id: 9,
    name: "Nasi goreng juara",
    imageSrc: "./src/assets/nasigoreng.jpg",
    imageAlt: "Food List",
    price: "25.000",
    location: "Bandung",
  },
  {
    id: 10,
    name: "Kwetiaw 79",
    imageSrc: "./src/assets/kwetiaw.jpeg",
    imageAlt: "Food List",
    price: "35.000",
    location: "Bandung",
  },
  {
    id: 11,
    name: "Bubur ABC",
    imageSrc: "./src/assets/bubur.jpg",
    imageAlt: "Food List",
    price: "15.000",
    location: "Bandung",
  },

  {
    id: 12,
    name: "Mie Ramen Paster",
    imageSrc: "./src/assets/ramen.jpg",
    imageAlt: "Food List",
    price: "25.000",
    location: "Bandung",
  },
  {
    id: 13,
    name: "Martabak Mang adek",
    imageSrc: "./src/assets/martabak.jpg",
    imageAlt: "Food List",
    price: "45.000",
    location: "Bandung",
  },
  {
    id: 14,
    name: "Steak BDG",
    imageSrc: "./src/assets/steak.jpg",
    imageAlt: "Food List",
    price: "225.000",
    location: "Bandung",
  },
];

export default foodLists;
